// Builds data/career.js (window.CAREER, window.RACES) from the raw data files:
//   data/parkrun-results.json  – every parkrun result from the athlete's parkrun page
//   data/strava-runs.txt       – every Strava run (date + distance)
//   data/race-streams.json     – watch streams (distance, time, heart rate) for the two marathons
// Usage: node tools/build-data.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const EPOCH = Date.UTC(2016, 0, 1);
const dayNum = (iso) => Math.round((Date.parse(iso + 'T00:00:00Z') - EPOCH) / 86400000);
const mmss = (s) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;

// ---- Strava runs ----
const runs = [];
let year = null;
for (const raw of fs.readFileSync(path.join(root, 'data/strava-runs.txt'), 'utf8').split('\n')) {
  const line = raw.trim();
  const y = line.match(/^# year (\d{4})$/);
  if (y) { year = y[1]; continue; }
  if (!line || line.startsWith('#')) continue;
  const [md, m] = line.split(/\s+/);
  runs.push([dayNum(`${year}-${md}`), Number(m)]);
}
for (let i = 1; i < runs.length; i++) if (runs[i][0] < runs[i - 1][0]) throw new Error(`strava-runs.txt out of order near line ${i}`);

const years = {};
for (const [d, m] of runs) {
  const y = new Date(EPOCH + d * 86400000).getUTCFullYear();
  years[y] ??= { year: y, runs: 0, km: 0 };
  years[y].runs++;
  years[y].km += m / 1000;
}
const totalKm = runs.reduce((a, [, m]) => a + m, 0) / 1000;

// ---- parkrun ----
const pr = JSON.parse(fs.readFileSync(path.join(root, 'data/parkrun-results.json'), 'utf8')).results;
const events = [...new Set(pr.map((r) => r.event))];
const parkruns = pr.map((r) => [dayNum(r.date), r.seconds, r.position, events.indexOf(r.event), r.pb ? 1 : 0]);
let best = Infinity;
const pbStair = [];
for (const r of pr) if (r.seconds < best) { best = r.seconds; pbStair.push({ date: r.date, event: r.event, time: r.time, s: r.seconds }); }
let fbest = Infinity;
const finsburyStair = [];
for (const r of pr) {
  if (r.event !== 'Finsbury Park' || r.date > '2022-08-27') continue;
  if (r.seconds < fbest) { fbest = r.seconds; finsburyStair.push({ date: r.date, time: r.time, s: r.seconds }); }
}
const eventCounts = Object.fromEntries(events.map((e) => [e, pr.filter((r) => r.event === e).length]));
const fastest = pr.reduce((a, r) => (r.seconds < a.seconds ? r : a));
const mean = Math.round(pr.reduce((a, r) => a + r.seconds, 0) / pr.length);

const CAREER = {
  built: new Date().toISOString().slice(0, 10),
  epoch: '2016-01-01',
  runs,
  parkruns,
  events,
  years: Object.values(years).map((y) => ({ ...y, km: Math.round(y.km) })),
  pbStair,
  finsburyStair,
  eventCounts,
  totals: {
    runs: runs.length,
    km: Math.round(totalKm),
    runDays: new Set(runs.map(([d]) => d)).size,
    longestKm: Math.max(...runs.map(([, m]) => m)) / 1000,
    parkruns: pr.length,
    events: events.length,
    coursePBs: pr.filter((r) => r.pb).length,
    podiums: pr.filter((r) => r.position <= 3).length,
    fastestParkrun: { time: fastest.time, event: fastest.event, date: fastest.date },
    meanParkrun: mmss(mean),
    firstParkrun: { date: pr[0].date, event: pr[0].event, time: pr[0].time, position: pr[0].position },
    latestParkrun: { date: pr.at(-1).date, event: pr.at(-1).event, time: pr.at(-1).time, position: pr.at(-1).position },
  },
};
const { source, ...races } = JSON.parse(fs.readFileSync(path.join(root, 'data/race-streams.json'), 'utf8'));
const out = `// Generated by tools/build-data.mjs from the files in data/. Do not edit.\nwindow.CAREER = ${JSON.stringify(CAREER)};\nwindow.RACES = ${JSON.stringify(races)};\n`;
fs.writeFileSync(path.join(root, 'data/career.js'), out);
console.log(`career.js: ${runs.length} runs, ${Math.round(totalKm)} km, ${pr.length} parkruns at ${events.length} events`);
console.log('years', CAREER.years.map((y) => `${y.year}:${y.runs}/${y.km}km`).join(' '));
console.log('pb stair', pbStair.map((p) => `${p.time}@${p.date}`).join(' '));
console.log('finsbury', finsburyStair.map((p) => p.time).join(' '));
